// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Likes       int    `json:"likes"`
	UserID      int    `json:"userId"`
	VideoID     int    `json:"videoId"`
}

type Playlist struct {
	ID      string `json:"id"`
	UserID  int    `json:"userId"`
	VideoID string `json:"videoId"`
	Name    string `json:"name"`
}

type User struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	TotalView     int       `json:"totalView"`
	PremiumMember bool      `json:"premiumMember"`
	JoinDate      time.Time `json:"joinDate"`
	Subscriber    int       `json:"subscriber"`
	Image         string    `json:"image"`
}

type Video struct {
	ID             string    `json:"id"`
	Category       string    `json:"category"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	AgeRestriction string    `json:"ageRestriction"`
	ViewCount      int       `json:"viewCount"`
	UploadDate     time.Time `json:"uploadDate"`
	UserID         int       `json:"userId"`
	Video          string    `json:"video"`
	Thumbnail      string    `json:"thumbnail"`
	Likes          int       `json:"likes"`
	Dislikes       int       `json:"dislikes"`
	Private        string    `json:"private"`
}

type NewComment struct {
	Description string `json:"description"`
	Likes       int    `json:"likes"`
	UserID      int    `json:"userId"`
	VideoID     int    `json:"videoId"`
}

type NewPlaylist struct {
	UserID  int    `json:"userId"`
	VideoID string `json:"videoId"`
	Name    string `json:"name"`
}

type NewPlaylistItem struct {
	VideoID string `json:"videoId"`
}

type NewUser struct {
	Name          string    `json:"name"`
	TotalView     int       `json:"totalView"`
	PremiumMember bool      `json:"premiumMember"`
	JoinDate      time.Time `json:"joinDate"`
	Subscriber    int       `json:"subscriber"`
	Image         string    `json:"image"`
}

type NewVideo struct {
	Category       string    `json:"category"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	AgeRestriction string    `json:"ageRestriction"`
	ViewCount      int       `json:"viewCount"`
	UploadDate     time.Time `json:"uploadDate"`
	UserID         int       `json:"userId"`
	Video          string    `json:"video"`
	Thumbnail      string    `json:"thumbnail"`
	Likes          int       `json:"likes"`
	Dislikes       int       `json:"dislikes"`
	Private        string    `json:"private"`
}

type UpdateComment struct {
	Description string `json:"description"`
}

type UpdateVideo struct {
	Category       string `json:"category"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	AgeRestriction string `json:"ageRestriction"`
	Private        string `json:"private"`
}
